In [1]:
import pandas as pd

# df = pd.read_csv('olympics.csv')
# df.head()

In [19]:
df = pd.read_csv('olympics.csv', index_col=0, skiprows=1)
df

№ Summer  01 !  02 !  03 !  \
Afghanistan (AFG)                                   13     0     0     2   
Algeria (ALG)                                       12     5     2     8   
Argentina (ARG)                                     23    18    24    28   
Armenia (ARM)                                        5     1     2     9   
Australasia (ANZ) [ANZ]                              2     3     4     5   
Australia (AUS) [AUS] [Z]                           25   139   152   177   
Austria (AUT)                                       26    18    33    35   
Azerbaijan (AZE)                                     5     6     5    15   
Bahamas (BAH)                                       15     5     2     5   
Bahrain (BRN)                                        8     0     0     1   
Barbados (BAR) [BAR]                                11     0     0     1   
Belarus (BLR)                                        5    12    24    39   
Belgium (BEL)                                       25    37    52    53   
Bermuda (BER)                                       17     0     0     1   
Bohemia (BOH) [BOH] [Z]                              3     0     1     3   
Botswana (BOT)                                       9     0     1     0   
Brazil (BRA)                                        21    23    30    55   
British West Indies (BWI) [BWI]                      1     0     0     2   
Bulgaria (BUL) [H]                                  19    51    85    78   
Burundi (BDI)                                        5     1     0     0   
Cameroon (CMR)                                      13     3     1     1   
Canada (CAN)                                        25    59    99   121   
Chile (CHI) [I]                                     22     2     7     4   
China (CHN) [CHN]                                    9   201   146   126   
Colombia (COL)                                      18     2     6    11   
Costa Rica (CRC)                                    14     1     1     2   
Ivory Coast (CIV) [CIV]                             12     0     1     0   
Croatia (CRO)                                        6     6     7    10   
Cuba (CUB) [Z]                                      19    72    67    70   
Cyprus (CYP)                                         9     0     1     0   
...                                                ...   ...   ...   ...   
Sri Lanka (SRI) [SRI]                               16     0     2     0   
Sudan (SUD)                                         11     0     1     0   
Suriname (SUR) [E]                                  11     1     0     1   
Sweden (SWE) [Z]                                    26   143   164   176   
Switzerland (SUI)                                   27    47    73    65   
Syria (SYR)                                         12     1     1     1   
Chinese Taipei (TPE) [TPE] [TPE2]                   13     2     7    12   
Tajikistan (TJK)                                     5     0     1     2   
Tanzania (TAN) [TAN]                                12     0     2     0   
Thailand (THA)                                      15     7     6    11   
Togo (TOG)                                           9     0     0     1   
Tonga (TGA)                                          8     0     1     0   
Trinidad and Tobago (TRI) [TRI]                     16     2     5    11   
Tunisia (TUN)                                       13     3     3     4   
Turkey (TUR)                                        21    39    25    24   
Uganda (UGA)                                        14     2     3     2   
Ukraine (UKR)                                        5    33    27    55   
United Arab Emirates (UAE)                           8     1     0     0   
United States (USA) [P] [Q] [R] [Z]                 26   976   757   666   
Uruguay (URU)                                       20     2     2     6   
Uzbekistan (UZB)                                     5     5     5    10   
Venezuela (VEN)   

In [3]:
for col in df.columns:
    if col[:2]=='01':
        df.rename(columns={col:'Gold'+col[4:]}, inplace=True)
    if col[:2]=='02':
        df.rename(columns={col:'Silver'+col[4:]}, inplace=True)
    if col[:2]=='03':
        df.rename(columns={col:'Bronze'+col[4:]}, inplace=True)
    if col[:1]=='№':
        df.rename(columns={col:'#'+col[1:]}, inplace=True)

names_ids = df.index.str.split('(') # split the index by '('

df.index = names_ids.str[0] # the [0] element is the country name (new index) 
df['ID'] = names_ids.str[1].str[:3] # the [1] element is the abbreviation or ID (take first 3 characters from that)


df.head()

# Summer  Gold  Silver  Bronze  Total  # Winter  Gold.1  \
Afghanistan         13     0       0       2      2         0       0   
Algeria             12     5       2       8     15         3       0   
Argentina           23    18      24      28     70        18       0   
Armenia              5     1       2       9     12         6       0   
Australasia          2     3       4       5     12         0       0   

              Silver.1  Bronze.1  Total.1  # Games  Gold.2  Silver.2  \
Afghanistan          0         0        0       13       0         0   
Algeria              0         0        0       15       5         2   
Argentina            0         0        0       41      18        24   
Armenia              0         0        0       11       1         2   
Australasia          0         0        0        2       3         4   

              Bronze.2  Combined total   ID  
Afghanistan          2               2  AFG  
Algeria              8              15  ALG  
Argentina           28              70  ARG  
Armenia              9              12  ARM  
Australasia          5              12  ANZ

In [4]:
#Boolean masking : returning true over the desired condns and false over undesired ones
df['Gold'] >0

Afghanistan                          False
Algeria                               True
Argentina                             True
Armenia                               True
Australasia                           True
Australia                             True
Austria                               True
Azerbaijan                            True
Bahamas                               True
Bahrain                              False
Barbados                             False
Belarus                               True
Belgium                               True
Bermuda                              False
Bohemia                              False
Botswana                             False
Brazil                                True
British West Indies                  False
Bulgaria                              True
Burundi                               True
Cameroon                              True
Canada                                True
Chile                                 True
China      

In [5]:
# applying boolean mask over the data frame using where
only_gold = df.where(df['Gold'] > 0)
only_gold.head()      #prints NaN over undesired rows

# Summer  Gold  Silver  Bronze  Total  # Winter  Gold.1  \
Afghanistan        NaN   NaN     NaN     NaN    NaN       NaN     NaN   
Algeria           12.0   5.0     2.0     8.0   15.0       3.0     0.0   
Argentina         23.0  18.0    24.0    28.0   70.0      18.0     0.0   
Armenia            5.0   1.0     2.0     9.0   12.0       6.0     0.0   
Australasia        2.0   3.0     4.0     5.0   12.0       0.0     0.0   

              Silver.1  Bronze.1  Total.1  # Games  Gold.2  Silver.2  \
Afghanistan        NaN       NaN      NaN      NaN     NaN       NaN   
Algeria            0.0       0.0      0.0     15.0     5.0       2.0   
Argentina          0.0       0.0      0.0     41.0    18.0      24.0   
Armenia            0.0       0.0      0.0     11.0     1.0       2.0   
Australasia        0.0       0.0      0.0      2.0     3.0       4.0   

              Bronze.2  Combined total   ID  
Afghanistan        NaN             NaN  NaN  
Algeria            8.0            15.0  ALG  
Argentina         28.0            70.0  ARG  
Armenia            9.0            12.0  ARM  
Australasia        5.0            12.0  ANZ

In [6]:
only_gold['Gold'].count()      # doesnt count NaN

99

In [7]:
df['Gold'].count()

146

In [8]:
only_gold = only_gold.dropna()
only_gold.head()

# Summer   Gold  Silver  Bronze  Total  # Winter  Gold.1  \
Algeria           12.0    5.0     2.0     8.0   15.0       3.0     0.0   
Argentina         23.0   18.0    24.0    28.0   70.0      18.0     0.0   
Armenia            5.0    1.0     2.0     9.0   12.0       6.0     0.0   
Australasia        2.0    3.0     4.0     5.0   12.0       0.0     0.0   
Australia         25.0  139.0   152.0   177.0  468.0      18.0     5.0   

              Silver.1  Bronze.1  Total.1  # Games  Gold.2  Silver.2  \
Algeria            0.0       0.0      0.0     15.0     5.0       2.0   
Argentina          0.0       0.0      0.0     41.0    18.0      24.0   
Armenia            0.0       0.0      0.0     11.0     1.0       2.0   
Australasia        0.0       0.0      0.0      2.0     3.0       4.0   
Australia          3.0       4.0     12.0     43.0   144.0     155.0   

              Bronze.2  Combined total   ID  
Algeria            8.0            15.0  ALG  
Argentina         28.0            70.0  ARG  
Armenia            9.0            12.0  ARM  
Australasia        5.0            12.0  ANZ  
Australia        181.0           480.0  AUS

In [9]:
only_gold = df[df['Gold'] > 0]
only_gold.head()

# Summer  Gold  Silver  Bronze  Total  # Winter  Gold.1  \
Algeria             12     5       2       8     15         3       0   
Argentina           23    18      24      28     70        18       0   
Armenia              5     1       2       9     12         6       0   
Australasia          2     3       4       5     12         0       0   
Australia           25   139     152     177    468        18       5   

              Silver.1  Bronze.1  Total.1  # Games  Gold.2  Silver.2  \
Algeria              0         0        0       15       5         2   
Argentina            0         0        0       41      18        24   
Armenia              0         0        0       11       1         2   
Australasia          0         0        0        2       3         4   
Australia            3         4       12       43     144       155   

              Bronze.2  Combined total   ID  
Algeria              8              15  ALG  
Argentina           28              70  ARG  
Armenia              9              12  ARM  
Australasia          5              12  ANZ  
Australia          181             480  AUS

In [10]:
# create mask for countries received gold in summer OR winter olympics
len(df[(df['Gold'] > 0) | (df['Gold.1'] > 0)])

100

In [11]:
df[(df['Gold.1'] > 0) & (df['Gold'] == 0)]

# Summer  Gold  Silver  Bronze  Total  # Winter  Gold.1  \
Liechtenstein         16     0       0       0      0        18       2   

                Silver.1  Bronze.1  Total.1  # Games  Gold.2  Silver.2  \
Liechtenstein          2         5        9       34       2         2   

                Bronze.2  Combined total   ID  
Liechtenstein          5               9  LIE

## question 0
what is the first country in df

In [12]:
def func1():
    return df.iloc[0]
func1()

# Summer           13
Gold                0
Silver              0
Bronze              2
Total               2
# Winter            0
Gold.1              0
Silver.1            0
Bronze.1            0
Total.1             0
# Games            13
Gold.2              0
Silver.2            0
Bronze.2            2
Combined total      2
ID                AFG
Name: Afghanistan , dtype: object

### Question 1
Which country has won the most gold medals in summer games?

*This function should return a single string value.*

In [13]:
# Return index of first occurrence of maximum over requested axis
def answer_one():
    return df['Gold'].idxmax()      #best

answer_one()

'United States\xa0'

### Question 2
Which country had the biggest difference between their summer and winter gold medal counts?

This function should return a single string value

In [14]:
def answer_two():
    return (df['Gold'] - df['Gold.1']).idxmax()
answer_two()

'United States\xa0'

### Question 3
Which country has the biggest difference between their summer gold medal counts and winter gold medal counts relative to their total gold medal count? 

$$\frac{Summer~Gold - Winter~Gold}{Total~Gold}$$

Only include countries that have won at least 1 gold in both summer and winter.

*This function should return a single string value.*

In [15]:
def answer_three():
    x = df.where((df['Gold'] > 0) & (df['Gold.1'] > 0))
    x = x.dropna()
    return abs((x['Gold'] - x['Gold.1']) / x['Gold.2']).idxmax()

answer_three()

'Bulgaria\xa0'

### Question 4
Write a function that creates a Series called "Points" which is a weighted value where each gold medal (Gold.2) counts for 3 points, silver medals (Silver.2) for 2 points, and bronze medals (Bronze.2) for 1 point. The function should return only the column (a Series object) which you created, with the country names as indices.

This function should return a Series named Points of length 146

In [16]:
def answer_four():
    df['Points'] = (df['Gold.2']*3 + df['Silver.2']*2 + df['Bronze.2']*1)
    return df['Points']
answer_four()

Afghanistan                             2
Algeria                                27
Argentina                             130
Armenia                                16
Australasia                            22
Australia                             923
Austria                               569
Azerbaijan                             43
Bahamas                                24
Bahrain                                 1
Barbados                                1
Belarus                               154
Belgium                               276
Bermuda                                 1
Bohemia                                 5
Botswana                                2
Brazil                                184
British West Indies                     2
Bulgaria                              411
Burundi                                 3
Cameroon                               12
Canada                                846
Chile                                  24
China                             

## Part 2
For the next set of questions, we will be using census data from the [United States Census Bureau](http://www.census.gov). Counties are political and geographic subdivisions of states in the United States. This dataset contains population data for counties and states in the US from 2010 to 2015. [See this document](https://www2.census.gov/programs-surveys/popest/technical-documentation/file-layouts/2010-2015/co-est2015-alldata.pdf) for a description of the variable names.

The census dataset (census.csv) should be loaded as census_df. Answer questions using this as appropriate.

### Question 5
Which state has the most counties in it? (hint: consider the sumlevel key carefully! You'll need this for future questions too...)

*This function should return a single string value.*

In [17]:
# GROUPING AND AGGREGATION
import pandas as pd
df = pd.read_csv('census.csv')

def answer_five():
    new_df = df[df['SUMLEV'] ==50]
    print(type(new_df.groupby('STNAME').count()['SUMLEV'].idxmax()))    #OR USE .SUMLEV instead
    return new_df.groupby('STNAME').count().SUMLEV.idxmax()      #idxmax used cz we need index of city with largest counties 
answer_five()

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 2: invalid continuation byte

### Question 6
**Only looking at the three most populous counties for each state**, what are the three most populous states (in order of highest population to lowest population)? Use `CENSUS2010POP`.

*This function should return a list of string values.*

In [ ]:
def answer_six():
    new_df = df[df['SUMLEV'] == 50]
    most_populous_counties = new_df.sort_values('CENSUS2010POP', ascending=False).groupby('STNAME').head(3)
    return most_populous_counties.groupby('STNAME').sum().sort_values('CENSUS2010POP', ascending=False).head(3).index.tolist()

answer_six()

### Question 7
Which county has had the largest absolute change in population within the period 2010-2015? (Hint: population values are stored in columns POPESTIMATE2010 through POPESTIMATE2015, you need to consider all six columns.)

e.g. If County Population in the 5 year period is 100, 120, 80, 105, 100, 130, then its largest change in the period would be |130-80| = 50.

*This function should return a single string value.*

In [ ]:
def answer_seven():
    newdf = df[df['SUMLEV'] == 50]
    newdf['STDEV'] = newdf[['POPESTIMATE2010','POPESTIMATE2011','POPESTIMATE2012',
                      'POPESTIMATE2013','POPESTIMATE2014','POPESTIMATE2015']].std(axis=1)
    
    return newdf.loc[newdf['STDEV'].idxmax()]['CTYNAME']

answer_seven()

### Question 8
In this datafile, the United States is broken up into four regions using the "REGION" column. 

Create a query that finds the counties that belong to regions 1 or 2, whose name starts with 'Washington', and whose POPESTIMATE2015 was greater than their POPESTIMATE 2014.

*This function should return a 5x2 DataFrame with the columns = ['STNAME', 'CTYNAME'] and the same index ID as the census_df (sorted ascending by index).*

In [ ]:
def answer_eight():
    region_df = df[(df['REGION'] == 1) | (df['REGION'] == 2)]
    counties = region_df[(region_df['CTYNAME'] == 'Washington County') & (region_df['POPESTIMATE2015'] > region_df['POPESTIMATE2014'])]
    return counties[['STNAME','CTYNAME']]
answer_eight()

In [ ]:
def answer_eight():
    #ndf= df[df['SUMLEV'] == 50]
    region1 = df['REGION'] == 1
    region2 = df['REGION'] == 2
    county_name = df['CTYNAME'].str.startswith('Washington')
    pop_estim = df['POPESTIMATE2015'] > df['POPESTIMATE2014']
    df = df[(region2) | (region1) &county_name &pop_estim]
    return df[['STNAME', 'CTYNAME']]
answer_eight()